export const GENERATED_ASSET_NAMES = [
  'expand-dark.svg',
  'expand-mobile-dark.svg',
  'hero-dark.svg',
  'hero-static-dark.svg',
  'systems-dark.svg',
  'systems-static-dark.svg',
  'systems-mobile-dark.svg',
  'systems-mobile-static-dark.svg',
  'architecture-dark.svg',
  'architecture-static-dark.svg',
  'architecture-mobile-dark.svg',
  'architecture-mobile-static-dark.svg',
  'signal-dark.svg',
  'signal-static-dark.svg',
  'signal-mobile-dark.svg',
  'signal-mobile-static-dark.svg',
] as const;
