// One-time (re-runnable) vendoring step: copies the exact simple-icons path
// data for every technology V7.1 displays into repository-local files, so the
// generator and the published assets never depend on node_modules or any
// external host at build or render time.
//
// Outputs:
//   v7/assets/logos/<slug>.svg   — standalone 24x24 reference SVG per mark
//   v7/src/logos.ts              — checked-in path data consumed by generate.ts
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as si from 'simple-icons';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LOGO_DIR = resolve(ROOT, 'assets/logos');
const OUT_TS = resolve(ROOT, 'src/logos.ts');

interface Pick {
  slug: string;
  exportName: keyof typeof si;
}

// Every displayed technology mark. Keep this list in sync with
// v7/data/content.ts — QA cross-checks that each displayed technology
// resolves to a vendored mark.
const picks: Pick[] = [
  { slug: 'react', exportName: 'siReact' },
  { slug: 'typescript', exportName: 'siTypescript' },
  { slug: 'kubernetes', exportName: 'siKubernetes' },
  { slug: 'docker', exportName: 'siDocker' },
  { slug: 'nginx', exportName: 'siNginx' },
  { slug: 'apache', exportName: 'siApache' },
  { slug: 'redis', exportName: 'siRedis' },
  { slug: 'elasticsearch', exportName: 'siElasticsearch' },
  { slug: 'linux', exportName: 'siLinux' },
  { slug: 'ubuntu', exportName: 'siUbuntu' },
  { slug: 'debian', exportName: 'siDebian' },
  { slug: 'postgresql', exportName: 'siPostgresql' },
  { slug: 'pwa', exportName: 'siPwa' },
];

const version = JSON.parse(
  readFileSync(resolve(ROOT, '../node_modules/simple-icons/package.json'), 'utf8'),
).version as string;

mkdirSync(LOGO_DIR, { recursive: true });

const entries: string[] = [];
for (const { slug, exportName } of picks) {
  const icon = si[exportName] as { title: string; hex: string; path: string; license?: { type: string } };
  if (!icon?.path) throw new Error(`simple-icons export missing: ${String(exportName)}`);
  const license = icon.license?.type ?? 'CC0-1.0 (simple-icons set default)';
  const svg = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-label="${icon.title} logo">`,
    `<!-- ${icon.title} mark, vendored from simple-icons v${version}; icon license: ${license}. -->`,
    `<path fill="#${icon.hex}" d="${icon.path}"/>`,
    `</svg>`,
    '',
  ].join('\n');
  writeFileSync(resolve(LOGO_DIR, `${slug}.svg`), svg, 'utf8');
  entries.push(
    `  ${slug === 'pwa' ? 'pwa' : slug}: {\n` +
      `    title: ${JSON.stringify(icon.title)},\n` +
      `    brandHex: ${JSON.stringify('#' + icon.hex)},\n` +
      `    license: ${JSON.stringify(license)},\n` +
      `    path: ${JSON.stringify(icon.path)},\n` +
      `  },`,
  );
}

const ts = [
  '// GENERATED by v7/scripts/vendor-logos.ts — do not edit by hand.',
  `// Source: simple-icons v${version} (https://github.com/simple-icons/simple-icons),`,
  '// vendored locally so no build or render step touches the network.',
  '// See v7/assets/logos/SOURCES.md for the license and trademark strategy.',
  '',
  'export interface LogoMark {',
  '  title: string;',
  '  brandHex: string;',
  '  license: string;',
  '  /** Single path in a 24x24 viewBox. */',
  '  path: string;',
  '}',
  '',
  'export const logoMarks = {',
  ...entries,
  '} as const;',
  '',
  'export type LogoSlug = keyof typeof logoMarks;',
  '',
] .join('\n');

writeFileSync(OUT_TS, ts, 'utf8');
console.log(`vendored ${picks.length} marks from simple-icons v${version}`);
console.log(`wrote ${OUT_TS}`);
